apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  annotations:
    cnrm.cloud.google.com/auto-create-network: "false"
  name: mabenoit-tenant-735
  namespace: config-control
spec:
  name: mabenoit-tenant-735
  billingAccountRef:
    external: "01EA9E-528725-FACCCF"
  organizationRef:
    external: "655675970190"
  resourceID: mabenoit-tenant-735
