apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: mabenoit-tenant-735-storage-admin
  namespace: config-control
spec:
  member: serviceAccount:mabenoit-tenant-735@mabenoit-configcontroller.iam.gserviceaccount.com
  role: roles/storage.admin
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/mabenoit-tenant-735
