apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: syncs-repo
  namespace: mabenoit-tenant-735
subjects:
- kind: ServiceAccount
  name: ns-reconciler-mabenoit-tenant-735
  namespace: config-management-system
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
